name: Release

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          path: ./packages/forge-opencode
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: "@jadeit/forge-ai"

  publish:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          path: ./packages/forge-opencode
      - run: npm ci
      - run: npm run build --if-present
#      - run: npm test
      - run: npm publish
